### ISSUE TITLE
Course sections with no description or no modules aren't displayed

### ISSUE THREAD

**Issue by abhijeetviswa** [crux-bphc/CMS-Android#100]
Course sections that don't have an modules associated with it (just a name and/or description) aren't displayed. This can result in students missing out on important announcements made through this manner.

**Comment by arjav2002** [comment]
What do you mean? It's very clearly visible.
https://drive.google.com/open?id=1P35l_cGg5btCba1cCaVMsRSL5exhPhLB

**Comment by abhijeetviswa** [comment]
Create a course section and give it a description. Don't add any modules. You won't see it on the app but it'll be visible on the website.

**Comment by abhijeetviswa** [comment]
I'm still not sure how big of a problem this is. I did see on course in 2018-19 Sem 2 in which course section labels were used to provide information. Provided the section has a description, it shows up on the app (which is what most professors do). 

Moreover, every course has default sections `Topic 1`, `Topic 2`, `Topic 3`, and `Topic 4`. Some professors don't divide things using course sections and simply use `Topic 1` for everything. This means that if we choose to show empty course sections (i.e don't have modules or descriptions), then these Topic sections will also be shown (causing spam and distracting the user).

**Comment by abhijeetviswa** [comment]
Just noticed that in BITS F225 (2019-2020 Sem 2), the professor had added a variety of course sections for the sole purpose of notifying students. 

![image](https://user-images.githubusercontent.com/2743113/80859298-2c48f180-8c7d-11ea-9ae0-6b6b7a50e05f.png)

This might actually be more problematic than I originally though. Marking this has *high priority*. We need to show notifications for such sections as well.

**Comment by abhijeetviswa** [comment]
Talked to @punss (CMS-iOS) about this. 

The current way we are displaying sections might not be aesthetically fit to display sentences. So, it would be best to break a sentence (which can checked for it has more than 3 words) at the first word and display that as the title with the remaining being pushed to the summary. Trailing and leading ellipsis for added effect.

**Comment by abhijeetviswa** [comment]
#189 simply leaves the section title in the default layout. That works for now. We can change it later on.
