### ISSUE TITLE
Move Download Course button to underneath an ellipsis with Mark All As Read

### ISSUE THREAD

**Issue by VaishnaviShri** [crux-bphc/CMS-Android#174]
The download course button present under each course name is one of the rarely used options and occupies a majority of the space on the screen. This option can be included in a more option which can also include the frequently used "mark all as read"

![WhatsApp Image 2020-04-25 at 4 34 03 PM](https://user-images.githubusercontent.com/58984760/80278304-ca373c00-8712-11ea-92de-8a9ab3160a7f.jpeg)
 option for the particular course.

**Comment by abhijeetviswa** [comment]
Closed by `a03e1d4bef56e7692d70e95c508b06bf26db4d21`.
