### ISSUE TITLE
Folder Module

### ISSUE THREAD

**Issue by harsu-ag** [crux-bphc/CMS-Android#23]
The folder contents and description need to be listed separately. 
A new activity (on-click the module) listing the contents.

Currently, when a folder is clicked all its contents are downloaded/opened recursively.

**Comment by harsu-ag** [comment]
This should apply not necessarily to folder module, but any module having more than 1 content.

**Comment by abhijeetviswa** [comment]
> This should apply not necessarily to folder module, but any module having more than 1 content.

I checked on the website and FILE modules which have more than one content only allow for the download for the first file. I'm not sure if we should add support for such modules which have more than one content if the website doesn't support it.
