### ISSUE TITLE
Plugin not enabled or configured

### ISSUE THREAD

**Issue by JacksiroKe** [crux-bphc/CMS-Android#238]
Running this app with my moodle installation fails when I click on the google SSO button giving the error on the browser as:

Debug Info:
Error code:
pluginnotenabledorconfigured

Stack trace:
line 57 of /admin/tool/mobile/launch.php: moodle_exception thrown

What could I be missing on my end to make this error go away?

**Comment by abhijeetviswa** [comment]
We use the OAuth2 plugin on our Moodle server to allow Google SSO on the website. I believe enabling this plugin should fix the issue for you. Also, the app uses a method similar to the official Moodle app to authenticate the user on the app.

**Comment by JacksiroKe** [comment]
I didn't have any problem with the official moodle app as soon as I enabled it from the moodle dashboard. But thanks a lot for the tip now I can go ahead and do that

**Comment by JacksiroKe** [comment]
Can the login be done without auth plugins to make things simpler?

**Comment by abhijeetviswa** [comment]
Our college's Moodle uses Google SSO to make things easier i.e username/password login has been disabled for students and teachers. We used to ask for the Web Service token (available for the website) as an "authentication" mechanism. We finally switched to Google SSO on this app in 7e6de3a671c9e44501399e3be2ecca8d8a0e0aa9. Feel free to fork this project and change the authentication method as per your need.

**Comment by fynngodau** [comment]
@JacksiroKe Just a little hint: in [our fork of the project](https://codeberg.org/fynngodau/moodleDirect), we implemented login through username and password. There are no releaes yet and development has haltet atm but maybe it could be useful to you in some way.

**Comment by JacksiroKe** [comment]
thanks so much that link was helpful
