### ISSUE TITLE
Winter of Code Project Idea

### ISSUE THREAD

**Issue by aero31aero** [crux-bphc/CMS-Android#25]
Topic: CMS BPHC
Project: 
1. As of now users get notification for every registered courses. The Plan is to add functionality so that students can select courses for which they would like to receive notifications.

2. The notifications are provided by running a background service periodically using IntentService. Apply the same logic using Firebase JobScheduler.

3. (Optional, if time permits): Shift to MVP architecture.
Skills Required: RecyclerView, Realm Database, Retrofit2, IntentService.
Optional Skills (for 3rd point): RxJava, Dagger2

**Comment by harsu-ag** [comment]
Firebase job scheduler has been done. 
@SKrPl can you add some more points here?

**Comment by harsu-ag** [comment]
Also 

1.  Add firebase Crash Reporting. 
2. In course filter for file names, headers.

**Comment by aero31aero** [comment]
I'm closing this issue as stale.
