### ISSUE TITLE
Issue with the notification body

### ISSUE THREAD

**Issue by saiankit** [crux-bphc/CMS-Android#261]
### The text in the Notification Body is not properly shown.

The **HTML** tages ( such as  \<p> , \<div>, \<href> ) are left behind without converting them to **Regular Text**.

##### Attached the screenshot for a better understanding of the issue.

![NotificationIssueCMSAndroid](https://user-images.githubusercontent.com/50326918/96248304-fac4a800-0fc8-11eb-95fb-42456993f118.jpeg)

**Comment by abhijeetviswa** [comment]
Thank you for creating an issue. This is a regression from ` c18f4112` if I'm not wrong.  Would you like to work on this?

**Comment by saiankit** [comment]
> Thank you for creating an issue. This is a regression from ` c18f4112` if I'm not wrong. Would you like to work on this?

No. I am not into Android Development. 
Wanted to report a bug that is evident from the latest CMS Update.
