### ISSUE TITLE
Improper text & image rendering in announcement

### ISSUE THREAD

**Issue by mvoggu** [crux-bphc/CMS-Android#303]
![cms_announcement](https://user-images.githubusercontent.com/50870617/104849171-537c4780-590e-11eb-8ef3-708fc51b24fd.jpeg)
* overlapping text
* png images not rendered properly

Above is an announcement from course BIO F451 and can be found at https://cms.bits-hyderabad.ac.in/mod/forum/discuss.php?d=22230
App Version: 1.8.2
Device: Mi A2

**Comment by abhijeetviswa** [comment]
Thanks for the report. Images won't be rendered properly since we are using a basic TextView. I'm not sure how big the use case is to warrant a switch to WebViews everywhere.

**Comment by abhijeetviswa** [comment]
Can you please test out #306? I wasn't able to test it against this specific announcement since it's too small and the extent of overlap is too little on my device. I did test it with huge walls of text though.

**Comment by mvoggu** [comment]
@abhijeetviswa fixed :)
![Screenshot_20210302-181653](https://user-images.githubusercontent.com/50870617/109652405-c15e9480-7b85-11eb-9014-decf6e9d0239.png)

**Comment by abhijeetviswa** [comment]
That's good to know. I'll merge it in.
