### ISSUE TITLE
CMS API url changed

### ISSUE THREAD

**Issue by vineeth07** [crux-bphc/CMS-Android#68]
Since the CMS api url has been changed from https://id.bits-hyderabad.ac.in/ to https://td.bits-hyderabad.ac.in/. Due to this, the network calls are returning error responses.

**Comment by TheGamer007** [comment]
Fixed in [Commit 5bfafc3](https://github.com/crux-bphc/CMS-Android/commit/5bfafc352999dfe4b09aa91297717c62bde57377). 
Sorry, I made the push because your PR was taking time :stuck_out_tongue:

**Comment by vineeth07** [comment]
No problem 😀
