### ISSUE TITLE
Individual Notification channels for each course

### ISSUE THREAD

**Issue by shriakhilc** [crux-bphc/CMS-Android#81]
The Notification Channels in Oreo allow great customization and granularity of control to the user. Providing a channel for each course rather than a common "Updates" channel would allow them to assign a lower priority to courses they aren't interested in, or a higher importance level to others.

Creating channels is relatively simple. One only needs to fetch the course list from the server, and create channels for each course with the Channel ID string being, for example, the course ID which is unique and won't have problematic characters. The course name can be assigned as the title. 

When a user leaves a course, the channel will not be of use any longer. While leaving it around isn't a big deal considering that users enroll in a limited number of courses, it is inelegant. However, deletion of channels is logged in the  Settings page as "x channels deleted". This is visible to the user, and Google may decide to add some anti-spam policies in the future. Thus, unlike Realm, we cannot clear all the channels and make them according to the server response.

In addition, creation of channels should take place such that the failure of a server response doesn't impact it. Thus, points such as the NotifService and the MainActivity should be handling the creation, just before showing notifications or just after syncing courses.

**Comment by abhijeetviswa** [comment]
Since we moved to push notifications, this is no longer possible. Moodle/Airnotifier pushes notification through the default channel.
