### ISSUE TITLE
Improper formatting of tabular data in Label

### ISSUE THREAD

**Issue by TheGamer007** [crux-bphc/CMS-Android#86]
## Description
Spaces between columns (and line breaks between rows) are not being properly rendered in the app. Should be a simple fix once the String is printed to logcat and observed.

**Observed in course:** Digital Design L

## Expected Fix
Better formatting of the displayed post in the app. Need not be exactly the same as on website (due to lack of screen size). Just ensure that spacing is not removed, and add scrolling. Any other suitable solution is also fine.

## Screenshots
App:
![App Screenshot](https://user-images.githubusercontent.com/22165670/46597128-7e0ab380-cafc-11e8-8166-0a67baf8e8bc.png)

Website:
![Website Screenshot](https://user-images.githubusercontent.com/22165670/46597168-ab576180-cafc-11e8-8da5-fcb8f718dbe6.png)

**Comment by TheGamer007** [comment]
The post made used the HTML `<table>`  tag for formatting, which is currently unsupported by Android `TextView`s. Using a `WebView` is the general suggested solution. 

Replacing the current view with a `WebView` might cause issues in plain text rendering, and will force removal of the "See More / See Less" feature. Given the satisfactory performance for _most_ content, we will **not** be replacing this with a `WebView`.

Users are requested to use the "View on Website" button in the app bar to view the content on their local browser. 

Open to fixes when Android extends support, or if a backward-compatible solution is properly implemented.

**Comment by abhijeetviswa** [comment]
Closing this issue since it's a _wontfix_.
