### ISSUE TITLE
UX and UI Imporvement

### ISSUE THREAD

**Issue by agrawal-d** [crux-bphc/CMS-Android#91]
**The user interface of the app is boring.** 
Materialisation and adding visual reliefs through images, colours, and icons and typography, adding more padding to elements of the application, i.e. **making the app confirm to the new material design principles** can greatly improve the app's visual appeal.

**Comment by SKrPl** [comment]
@hereisdx thanks for the feedback. It would be great if you could point out the specific areas where UI/UX needs improvement by updating this issue, please use check-box for the same. Example:
- [ ] Padding in **Login Fragment**

And if you are interested, you can start working on it.

**Comment by hereisdx** [comment]
@SKrPl I haven't gone throught the project's source yet. I'll look at it after the compres and work on it as well as update the issue with the areas that I think need improvement. This is my first time working with an open source project. I look forward to improving the app!

**Comment by abhijeetviswa** [comment]
The latest beta release has an update UX and UI. We've tried to follow Material guidelines. Due to the broad nature of this issue, I'm closing this. Feel free to create more detailed issues that have specific suggestions.
