### ISSUE TITLE
Implicit links not working.

### ISSUE THREAD

**Issue by palindrome69** [crux-bphc/CMS-Android#92]
Any course content which is of a ‘link type’.  Say course EEE F245 has experiment 1 as one of the topics. The topic is not hyperlinked to the content. It’s just plain text.

**Comment by SKrPl** [comment]
@palindrome69 can you please update the issue description with screenshot(s) ?

**Comment by palindrome69** [comment]
![whatsapp image 2019-02-26 at 1 12 03 pm](https://user-images.githubusercontent.com/36225548/53395818-d158a200-39c8-11e9-960b-7cc76ed76a89.jpeg)

All experiments under topic 3 are supposed to be links to a pdf file instead it is plain text.

**Comment by SKrPl** [comment]
@palindrome69 thanks, will look into it soon
