### ISSUE TITLE
UI hangs on pressing 'Mark all as Read'

### ISSUE THREAD

**Issue by agrawal-d** [crux-bphc/CMS-Android#97]
Upon pressing the said button within any course, the UI hangs for a few hundred milliseconds.

**Comment by abhijeetviswa** [comment]
When this does happen, are the quite a few significant number of sections that have to be marked as read?

**Comment by hereisdx** [comment]
Dear Abhijeet,
While this issue happens regardless of the number of unread sections, the duration of the UI hanging is barely noticeable ( less than half a second ). I have not noticed yet how dependent it is on the no of unread sections, but can say that it occurs even when that number is small.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by abhijeetviswa** [comment]
This has no longer been a problem since #80 was merged.
#320 further improves the 'Mark all as read' logic.
